features:
  -
    id: time_travel
    description: "Traveling through time"
    depends_on: delorean
    enablements:
      -
        method: ruby
        class_name: Enablement::TimeTravel
  -
    id: delorean
    description: "A shiny car"
  -
    id: space_travel
    description: "Traveling through space"
    enablements:
      -
        method: environment
        variable_name: SHELL
        matching: !ruby/regexp '/sh/'
        example: /bin/fish
      -
        method: environment
        variable_name: USER
        redact_value: true
