features:
  -
    id: time_travel
    description: "Traveling through time"
    enablements:
      -
        method: ruby
        class_name: Enablement::TimeTravel
  -
    id: space_travel
    description: "Traveling through space"
    enablements:
      -
        method: environment
        variable_name: SHELL
        matching: !ruby/regexp '/.+/'
      -
        method: environment
        variable_name: USER
        matching: !ruby/regexp '/.+/'
        redact_value: true
